-- RETIRED — DO NOT RUN THIS FILE.
--
-- This project previously used this file to create an insecure prototype
-- schema. It included a writable profile role, public payment receipts, and
-- legacy tables that are not part of the launch application.
--
-- The active production schema is the connected Supabase project. It uses
-- separate user_roles, private payment receipts, payment review records,
-- enrolments, lesson_progress, and row-level security policies.
--
-- Before the first deployment, export the remote migration history into a
-- tracked supabase/migrations directory using the Supabase CLI. Do not use
-- this retired script as a schema source.
